// AUTO-GENERATED by scripts/make-logo.mjs — a 1-bit dithered Earth, made with
// this tool's own ordered-dither. Inherits theme colour via currentColor.
export function EarthLogo({ className }: { className?: string }) {
  return (
    <svg
      viewBox="0 0 20 20"
      className={className}
      fill="currentColor"
      shapeRendering="crispEdges"
      role="img"
      aria-label="1bit.world"
    >
      <path d="M6 1h1v1h-1zM8 1h3v1h-3zM13 1h1v1h-1zM4 2h1v1h-1zM9 2h1v1h-1zM11 2h1v1h-1zM13 2h1v1h-1zM15 2h1v1h-1zM3 3h2v1h-2zM8 3h9v1h-9zM3 4h1v1h-1zM7 4h1v1h-1zM9 4h1v1h-1zM11 4h1v1h-1zM13 4h1v1h-1zM15 4h1v1h-1zM17 4h1v1h-1zM2 5h2v1h-2zM6 5h12v1h-12zM1 6h1v1h-1zM3 6h1v1h-1zM7 6h1v1h-1zM9 6h1v1h-1zM11 6h1v1h-1zM13 6h1v1h-1zM15 6h3v1h-3zM1 7h4v1h-4zM6 7h13v1h-13zM1 8h1v1h-1zM3 8h1v1h-1zM7 8h1v1h-1zM9 8h1v1h-1zM11 8h1v1h-1zM13 8h1v1h-1zM15 8h1v1h-1zM17 8h1v1h-1zM0 9h5v1h-5zM6 9h7v1h-7zM14 9h5v1h-5zM0 10h2v1h-2zM3 10h1v1h-1zM5 10h1v1h-1zM7 10h1v1h-1zM9 10h1v1h-1zM16 10h2v1h-2zM19 10h1v1h-1zM1 11h2v1h-2zM4 11h9v1h-9zM16 11h1v1h-1zM18 11h1v1h-1zM3 12h1v1h-1zM5 12h1v1h-1zM7 12h1v1h-1zM9 12h1v1h-1zM11 12h1v1h-1zM2 13h11v1h-11zM14 13h1v1h-1zM18 13h1v1h-1zM3 14h1v1h-1zM5 14h1v1h-1zM7 14h1v1h-1zM9 14h1v1h-1zM11 14h1v1h-1zM13 14h1v1h-1zM2 15h13v1h-13zM16 15h1v1h-1zM3 16h1v1h-1zM5 16h1v1h-1zM7 16h1v1h-1zM9 16h1v1h-1zM11 16h1v1h-1zM13 16h1v1h-1zM4 17h11v1h-11zM8 18h2v1h-2zM13 18h1v1h-1zM10 19h1v1h-1z" />
    </svg>
  );
}
