// Generates components/ui/EarthLogo.tsx: a 1-bit dithered Earth, produced with
// the same ordered-dither math the app uses. Emitted as an inline SVG path so
// it scales crisply and inherits the theme colour via `currentColor`.
import { writeFileSync } from "node:fs";

const N = 36; // grid (logo is N×N cells)
const c = (N - 1) / 2;
const R = N * 0.47;

// --- value-noise fbm for continents -----------------------------------------
const hash = (n) => {
  const s = Math.sin(n) * 43758.5453;
  return s - Math.floor(s);
};
function vnoise(x, y) {
  const xi = Math.floor(x);
  const yi = Math.floor(y);
  const xf = x - xi;
  const yf = y - yi;
  const tl = hash(xi * 157.1 + yi * 113.7);
  const tr = hash((xi + 1) * 157.1 + yi * 113.7);
  const bl = hash(xi * 157.1 + (yi + 1) * 113.7);
  const br = hash((xi + 1) * 157.1 + (yi + 1) * 113.7);
  const u = xf * xf * (3 - 2 * xf);
  const v = yf * yf * (3 - 2 * yf);
  return tl * (1 - u) * (1 - v) + tr * u * (1 - v) + bl * (1 - u) * v + br * u * v;
}
function fbm(x, y) {
  let a = 0;
  let amp = 0.5;
  let f = 1;
  for (let i = 0; i < 4; i++) {
    a += amp * vnoise(x * f, y * f);
    f *= 2;
    amp *= 0.5;
  }
  return a;
}

// Light direction (upper-left) for a subtle 3D read.
const L = (() => {
  const v = [-0.4, -0.5, 0.78];
  const m = Math.hypot(...v);
  return v.map((n) => n / m);
})();

// --- shaded globe → grayscale -----------------------------------------------
const gray = new Float32Array(N * N);
const inside = new Uint8Array(N * N);
for (let y = 0; y < N; y++) {
  for (let x = 0; x < N; x++) {
    const dx = (x - c) / R;
    const dy = (y - c) / R;
    const d2 = dx * dx + dy * dy;
    const i = y * N + x;
    if (d2 > 1) continue;
    inside[i] = 1;
    const z = Math.sqrt(1 - d2);
    const lon = Math.atan2(dx, z);
    const lat = Math.asin(Math.max(-1, Math.min(1, dy)));
    const land = fbm(lon * 1.7 + 3.1, lat * 1.9 + 1.4) > 0.52;
    const albedo = land ? 0.92 : 0.42;
    const limb = 0.55 + 0.45 * z; // darker toward the rim
    const dot = Math.max(0, dx * L[0] + dy * L[1] + z * L[2]);
    const light = 0.7 + 0.3 * dot;
    gray[i] = Math.max(0, Math.min(255, 255 * albedo * limb * light));
  }
}

// --- ordered (Bayer 4×4) dither → ink mask ----------------------------------
const B4 = [0, 8, 2, 10, 12, 4, 14, 6, 3, 11, 1, 9, 15, 7, 13, 5].map(
  (v) => (v + 0.5) / 16,
);
const mask = new Uint8Array(N * N);
for (let y = 0; y < N; y++) {
  for (let x = 0; x < N; x++) {
    const i = y * N + x;
    if (!inside[i]) continue;
    const t = B4[(y % 4) * 4 + (x % 4)] * 255;
    mask[i] = gray[i] < t ? 1 : 0;
  }
}

// --- emit SVG path (horizontal runs of ink cells) ---------------------------
let d = "";
for (let y = 0; y < N; y++) {
  let x = 0;
  while (x < N) {
    if (mask[y * N + x]) {
      let len = 1;
      while (x + len < N && mask[y * N + x + len]) len++;
      d += `M${x} ${y}h${len}v1h-${len}z`;
      x += len;
    } else {
      x++;
    }
  }
}

const tsx = `// AUTO-GENERATED by scripts/make-logo.mjs — a 1-bit dithered Earth, made with
// this tool's own ordered-dither. Inherits theme colour via currentColor.
export function EarthLogo({ className }: { className?: string }) {
  return (
    <svg
      viewBox="0 0 ${N} ${N}"
      className={className}
      fill="currentColor"
      shapeRendering="crispEdges"
      role="img"
      aria-label="1bit.world"
    >
      <path d="${d}" />
    </svg>
  );
}
`;

writeFileSync("components/ui/EarthLogo.tsx", tsx);
const cells = mask.reduce((a, b) => a + b, 0);
console.log(`wrote components/ui/EarthLogo.tsx (${N}×${N}, ${cells} ink cells, ${d.length} path chars)`);
